package xyz.jhofmann1.cs320.junit.model;

import static org.junit.Assert.*;

import org.junit.Test;

import xyz.jhofmann1.cs320.model.main.Club;

public class ClubsTest {

	@Test
	public void testAll(){
		assertEquals("AIGA, Graphic Arts & Design",Club.AGAD.getTitle());
		assertEquals(1,Club.AGAD.getID());
		assertEquals("Alpha Chi",Club.AC.getTitle());
		assertEquals(2,Club.AC.getID());
		assertEquals("American Criminal Justice Association",Club.ACJA.getTitle());
		assertEquals(3,Club.ACJA.getID());
		assertEquals("Anime Club",Club.AnC.getTitle());
		assertEquals(4,Club.AnC.getID());
		assertEquals("Best Buddies",Club.BB.getTitle());
		assertEquals(5,Club.BB.getID());
		assertEquals("Biology Club",Club.BC.getTitle());
		assertEquals(6,Club.BC.getID());
		assertEquals("Campus Activities Board",Club.CAB.getTitle());
		assertEquals(7,Club.CAB.getID());
		assertEquals("Chemistry Society",Club.CS.getTitle());
		assertEquals(8,Club.CS.getID());
		assertEquals("Club Baseball",Club.CB.getTitle());
		assertEquals(9,Club.CB.getID());
		assertEquals("Club Lacrosse",Club.CL.getTitle());
		assertEquals(10,Club.CL.getID());
		assertEquals("Club Softball",Club.ClS.getTitle());
		assertEquals(11,Club.ClS.getID());
		assertEquals("Club Volleyball",Club.CV.getTitle());
		assertEquals(12,Club.CV.getID());
		assertEquals("Colleges Against Cancer",Club.CAC.getTitle());
		assertEquals(13,Club.CAC.getID());
		assertEquals("Commuter Club",Club.CC.getTitle());
		assertEquals(14,Club.CC.getID());
		assertEquals("Dance Excel",Club.DE.getTitle());
		assertEquals(15,Club.DE.getID());
		assertEquals("Dance Team",Club.DT.getTitle());
		assertEquals(16,Club.DT.getID());
		assertEquals("Enactus",Club.E.getTitle());
		assertEquals(17,Club.E.getID());
		assertEquals("Equestrian Club",Club.EC.getTitle());
		assertEquals(18,Club.EC.getID());
		assertEquals("German Club",Club.GC.getTitle());
		assertEquals(19,Club.GC.getID());
		assertEquals("Gerontology Club",Club.GeC.getTitle());
		assertEquals(20,Club.GeC.getID());
		assertEquals("Habitat for Humanity",Club.HfH.getTitle());
		assertEquals(21,Club.HfH.getID());
		assertEquals("Hillel",Club.H.getTitle());
		assertEquals(22,Club.H.getID());
		assertEquals("Hispanic Cultural Society",Club.HCS.getTitle());
		assertEquals(23,Club.HCS.getID());
		assertEquals("History and International Studies Professional Organization",Club.HaISPO.getTitle());
		assertEquals(24,Club.HaISPO.getID());
		assertEquals("Ice Hockey",Club.IH.getTitle());
		assertEquals(25,Club.IH.getID());
		assertEquals("Inter-Varsity Christian Fellowship",Club.ICF.getTitle());
		assertEquals(26,Club.ICF.getID());
		assertEquals("LAMBDA: LGBT Alliance",Club.LLA.getTitle());
		assertEquals(27,Club.LLA.getID());
		assertEquals("National Association for Music Educators",Club.NAfME.getTitle());
		assertEquals(28,Club.NAfME.getID());
		assertEquals("Newman Club",Club.NC.getTitle());
		assertEquals(29,Club.NC.getID());
		assertEquals("Peer Support Network",Club.PSN.getTitle());
		assertEquals(30,Club.PSN.getID());
		assertEquals("Pre-Law Society",Club.PLS.getTitle());
		assertEquals(31,Club.PLS.getID());
		assertEquals("Pre-Medical Society",Club.PMS.getTitle());
		assertEquals(32,Club.PMS.getID());
		assertEquals("Public Relations Student Society of America",Club.PRSSoA.getTitle());
		assertEquals(33,Club.PRSSoA.getID());
		assertEquals("Psychology Club",Club.PC.getTitle());
		assertEquals(34,Club.PC.getID());
		assertEquals("Rhapsody",Club.R.getTitle());
		assertEquals(35,Club.R.getID());
		assertEquals("Role Playing Games Club",Club.RPGC.getTitle());
		assertEquals(36,Club.RPGC.getID());
		assertEquals("Rugby Team",Club.RT.getTitle());
		assertEquals(37,Club.RT.getID());
		assertEquals("Student Alumni Association",Club.SAA.getTitle());
		assertEquals(38,Club.SAA.getID());
		assertEquals("Student Education Association",Club.SEA.getTitle());
		assertEquals(39,Club.SEA.getID());
		assertEquals("Ski and Outdoor Club",Club.SaOC.getTitle());
		assertEquals(40,Club.SaOC.getID());
		assertEquals("Student Nurses Association of PA",Club.SNAoP.getTitle());
		assertEquals(41,Club.SNAoP.getID());
		assertEquals("Sport Management Student Association",Club.SMSA.getTitle());
		assertEquals(42,Club.SMSA.getID());
		assertEquals("Student Senate",Club.SS.getTitle());
		assertEquals(43,Club.SS.getID());
		assertEquals("The Spartan: The York College Newspaper",Club.TSTYCN.getTitle());
		assertEquals(44,Club.TSTYCN.getID());
		assertEquals("Ultimate Frisbee",Club.UF.getTitle());
		assertEquals(45,Club.UF.getID());
		assertEquals("Unity Club",Club.UC.getTitle());
		assertEquals(46,Club.UC.getID());
		assertEquals("WVYC: The York College Radio Station",Club.WTYCRS.getTitle());
		assertEquals(47,Club.WTYCRS.getID());
		assertEquals("YCP Film Society",Club.YFS.getTitle());
		assertEquals(48,Club.YFS.getID());
		assertEquals("YCP for Liberty",Club.YfL.getTitle());
		assertEquals(49,Club.YfL.getID());
		assertEquals("YCP Improv Troupe",Club.YIT.getTitle());
		assertEquals(50,Club.YIT.getID());
		assertEquals("York Environmental Society",Club.YES.getTitle());
		assertEquals(51,Club.YES.getID());
		assertEquals("York College Conservative Forum",Club.YCCF.getTitle());
		assertEquals(52,Club.YCCF.getID());
		assertEquals("Other",Club.O.getTitle());
		assertEquals(53,Club.O.getID());
	}
}
