package xyz.jhofmann1.cs320.junit.model;

import static org.junit.Assert.*;

import org.junit.Test;

import xyz.jhofmann1.cs320.model.main.Major;

public class MajorsTest {

	@Test
	public void testAll(){
		assertEquals("Accounting",Major.AC.getTitle());
		assertEquals(1,Major.AC.getID());
		assertEquals("Advertising and Digital Marketing",Major.AaDM.getTitle());
		assertEquals(2,Major.AaDM.getID());
		assertEquals("Biology",Major.BIO.getTitle());
		assertEquals(3,Major.BIO.getID());
		assertEquals("Business Administration",Major.BA.getTitle());
		assertEquals(4,Major.BA.getID());
		assertEquals("Business Administration A.S",Major.BAAD.getTitle());
		assertEquals(5,Major.BAAD.getID());
		assertEquals("Business Analytics",Major.BAn.getTitle());
		assertEquals(6,Major.BAn.getID());
		assertEquals("Chemistry",Major.CHEM.getTitle());
		assertEquals(7,Major.CHEM.getID());
		assertEquals("Civil Engineering",Major.CiVE.getTitle());
		assertEquals(8,Major.CiVE.getID());
		assertEquals("Computer Engineering",Major.CompE.getTitle());
		assertEquals(9,Major.CompE.getID());
		assertEquals("Computer Science",Major.CompSci.getTitle());
		assertEquals(10,Major.CompSci.getID());
		assertEquals("Criminal Justice",Major.CJ.getTitle());
		assertEquals(11,Major.CJ.getID());
		assertEquals("Cybersecurity Management",Major.CM.getTitle());
		assertEquals(12,Major.CM.getID());
		assertEquals("Early Elementary Education",Major.EEE.getTitle());
		assertEquals(13,Major.EEE.getID());
		assertEquals("Early Elementary/Special Education",Major.EESE.getTitle());
		assertEquals(14,Major.EESE.getID());
		assertEquals("Economics",Major.Econ.getTitle());
		assertEquals(15,Major.Econ.getID());
		assertEquals("Electrical Engineering",Major.EE.getTitle());
		assertEquals(16,Major.EE.getID());
		assertEquals("Engineering Management",Major.EM.getTitle());
		assertEquals(17,Major.EM.getID());
		assertEquals("English",Major.Eng.getTitle());
		assertEquals(18,Major.Eng.getID());
		assertEquals("Entrepreneurship and Innovation",Major.EI.getTitle());
		assertEquals(19,Major.EI.getID());
		assertEquals("Finance",Major.Fin.getTitle());
		assertEquals(20,Major.Fin.getID());
		assertEquals("Fine Art",Major.FA.getTitle());
		assertEquals(21,Major.FA.getID());
		assertEquals("Forensic Chemeistry",Major.FC.getTitle());
		assertEquals(22,Major.FC.getID());
		assertEquals("Graphic Design",Major.GD.getTitle());
		assertEquals(23,Major.GD.getID());
		assertEquals("History",Major.Hist.getTitle());
		assertEquals(24,Major.Hist.getID());
		assertEquals("Hospitality Management",Major.HM.getTitle());
		assertEquals(25,Major.HM.getID());
		assertEquals("Human Resource Management",Major.HRM.getTitle());
		assertEquals(26,Major.HRM.getID());
		assertEquals("Human Services",Major.HS.getTitle());
		assertEquals(27,Major.HS.getID());
		assertEquals("Information Technology Management",Major.ITM.getTitle());
		assertEquals(28,Major.ITM.getID());
		assertEquals("Intelligence Analysis",Major.IA.getTitle());
		assertEquals(29,Major.IA.getID());
		assertEquals("Internation Relations",Major.IR.getTitle());
		assertEquals(30,Major.IR.getID());
		assertEquals("Leadership and Organizational Dynamics",Major.LOD.getTitle());
		assertEquals(31,Major.LOD.getID());
		assertEquals("Marketing",Major.Market.getTitle());
		assertEquals(32,Major.Market.getID());
		assertEquals("Mass Communications",Major.MC.getTitle());
		assertEquals(33,Major.MC.getID());
		assertEquals("Mathematics",Major.Math.getTitle());
		assertEquals(34,Major.Math.getID());
		assertEquals("Mechanical Engineering",Major.ME.getTitle());
		assertEquals(35,Major.ME.getID());
		assertEquals("Medical Lab Science",Major.MLS.getTitle());
		assertEquals(36,Major.MLS.getID());
		assertEquals("Middle Level Education",Major.MLE.getTitle());
		assertEquals(37,Major.MLE.getID());
		assertEquals("Middle Level/Special Education",Major.MLSE.getTitle());
		assertEquals(38,Major.MLSE.getID());
		assertEquals("Music",Major.Music.getTitle());
		assertEquals(39,Major.Music.getID());
		assertEquals("Music Education",Major.MusicE.getTitle());
		assertEquals(40,Major.MusicE.getID());
		assertEquals("Music Industry/Recording Technology",Major.MIRT.getTitle());
		assertEquals(41,Major.MIRT.getID());
		assertEquals("Nuclear Medicine Technology",Major.NMT.getTitle());
		assertEquals(42,Major.NMT.getID());
		assertEquals("Nursing",Major.Nurse.getTitle());
		assertEquals(43,Major.Nurse.getID());
		assertEquals("Philosophy",Major.Philo.getTitle());
		assertEquals(44,Major.Philo.getID());
		assertEquals("Political Science",Major.PS.getTitle());
		assertEquals(45,Major.PS.getID());
		assertEquals("Professional Writing",Major.PW.getTitle());
		assertEquals(46,Major.PW.getID());
		assertEquals("Pyschology",Major.Pysch.getTitle());
		assertEquals(47,Major.Pysch.getID());
		assertEquals("Public Relations",Major.PR.getTitle());
		assertEquals(48,Major.PR.getID());
		assertEquals("RN to BS in Nursing",Major.RBN.getTitle());
		assertEquals(49,Major.RBN.getID());
		assertEquals("Radiography",Major.Radio.getTitle());
		assertEquals(50,Major.Radio.getID());
		assertEquals("Recreation and Leisure Administration",Major.RLA.getTitle());
		assertEquals(51,Major.RLA.getID());
		assertEquals("Respiratory Care",Major.RC.getTitle());
		assertEquals(52,Major.RC.getID());
		assertEquals("Secondary Education Biology",Major.SEB.getTitle());
		assertEquals(53,Major.SEB.getID());
		assertEquals("Secondary Education English",Major.SEE.getTitle());
		assertEquals(54,Major.SEE.getID());
		assertEquals("Secondary Education General Science",Major.SEGS.getTitle());
		assertEquals(55,Major.SEGS.getID());
		assertEquals("Secondary Education Mathematics",Major.SEM.getTitle());
		assertEquals(56,Major.SEM.getID());
		assertEquals("Secondary Education Social Studies",Major.SESS.getTitle());
		assertEquals(57,Major.SESS.getID());
		assertEquals("Self-Designed",Major.SD.getTitle());
		assertEquals(58,Major.SD.getID());
		assertEquals("Social Enterprise and Not-for-Profit Management",Major.SENM.getTitle());
		assertEquals(59,Major.SENM.getID());
		assertEquals("Sociology",Major.Soc.getTitle());
		assertEquals(60,Major.Soc.getID());
		assertEquals("Spanish Education",Major.SE.getTitle());
		assertEquals(61,Major.SE.getID());
		assertEquals("Spanish/Español",Major.Spanish.getTitle());
		assertEquals(62,Major.Spanish.getID());
		assertEquals("Sports Management",Major.SM.getTitle());
		assertEquals(63,Major.SM.getID());
		assertEquals("Supply Chain Operations Management",Major.SCOM.getTitle());
		assertEquals(64,Major.SCOM.getID());
		assertEquals("Theatre",Major.Theatre.getTitle());
		assertEquals(65,Major.Theatre.getID());
		assertEquals("Undeclared Business",Major.UB.getTitle());
		assertEquals(66,Major.UB.getID());
	}
}
